import pandas as pd
import os

def export_action_plan(analysis_df):
    """Generates a text file list of exactly what needs to be bought."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    report_path = os.path.join(project_root, 'data', 'purchase_order_suggestions.txt')
    
    with open(report_path, 'w') as f:
        f.write("=== WEEKLY PURCHASE ORDER SUGGESTIONS ===\n")
        f.write("Generated by: Inventory Forecasting System\n\n")
        
        critical_items = analysis_df[analysis_df['remaining_after_week'] < 0]
        
        if not critical_items.empty:
            f.write("--- !!! URGENT BUY LIST (STOCKOUT RISK) !!! ---\n")
            for _, row in critical_items.iterrows():
                shortfall = abs(row['remaining_after_week'])
                # Buy amount = Shortfall + Safety Buffer (Reorder Point)
                suggested_buy = shortfall + row['reorder_point']
                f.write(f"ORDER: {row['product']} | Amount: {int(suggested_buy)} units\n")
        else:
            f.write("All stock levels healthy for the upcoming week.\n")
            
    print(f"Action plan exported to: {report_path}")

def run_gap_analysis():
    print("!!! STARTING INVENTORY ANALYSIS !!!")
    
    # 1. Setup Paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    forecast_path = os.path.join(project_root, 'data', 'forecast_results.csv')
    stock_path = os.path.join(project_root, 'data', 'current_inventory.csv')

    # 2. Load the Data
    forecast_df = pd.read_csv(forecast_path)
    stock_df = pd.read_csv(stock_path)

    # 3. Aggregate Forecast
    total_forecast = forecast_df.groupby('product')['predicted_quantity'].sum().reset_index()
    total_forecast.columns = ['product', 'total_7day_demand']

    # 4. Merge Stock and Forecast
    analysis = pd.merge(stock_df, total_forecast, on='product')

    # 5. Calculate the Gap
    analysis['remaining_after_week'] = analysis['current_stock'] - analysis['total_7day_demand']
    
    # 6. Flag Alerts
    print("\n--- INVENTORY STATUS REPORT ---")
    for index, row in analysis.iterrows():
        status = "✅ OK"
        if row['remaining_after_week'] < 0:
            status = "🚨 CRITICAL: STOCKOUT RISK"
        elif row['remaining_after_week'] < row['reorder_point']:
            status = "⚠️ WARNING: REORDER SOON"
            
        print(f"Product: {row['product']}")
        print(f"  Current Stock: {row['current_stock']}")
        print(f"  Forecasted Demand (7 Days): {row['total_7day_demand']}")
        print(f"  Status: {status}")
        print("-" * 30)
    
    # 7. NEW: Trigger the text report
    export_action_plan(analysis)

if __name__ == "__main__":
    run_gap_analysis()